package com.probridge.expedite.dao.expdb;

import com.probridge.expedite.model.expdb.RoleInfo;
import com.probridge.expedite.model.expdb.RoleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int countByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int deleteByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int deleteByPrimaryKey(String roleName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    List<RoleInfo> selectByExample(RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    RoleInfo selectByPrimaryKey(String roleName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int updateByExampleSelective(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int updateByExample(@Param("record") RoleInfo record, @Param("example") RoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    int updateByPrimaryKey(RoleInfo record);
}