package com.probridge.expedite.dao.expdb;

import com.probridge.expedite.model.expdb.UserRolesExample;
import com.probridge.expedite.model.expdb.UserRolesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int deleteByPrimaryKey(UserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int insert(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int insertSelective(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    List<UserRolesKey> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Thu Mar 27 21:06:02 CST 2014
     */
    int updateByExample(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);
}