package com.probridge.expedite.model.expdb;

import java.io.Serializable;

public class RoleInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLE_INFO.role_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLE_INFO.app_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLE_INFO.form_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String formName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLE_INFO.description
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLE_INFO.data_limit
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private Integer dataLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPDB.EXPEDITE_ROLE_INFO
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLE_INFO.role_name
     *
     * @return the value of EXPDB.EXPEDITE_ROLE_INFO.role_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLE_INFO.role_name
     *
     * @param roleName the value for EXPDB.EXPEDITE_ROLE_INFO.role_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLE_INFO.app_name
     *
     * @return the value of EXPDB.EXPEDITE_ROLE_INFO.app_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLE_INFO.app_name
     *
     * @param appName the value for EXPDB.EXPEDITE_ROLE_INFO.app_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLE_INFO.form_name
     *
     * @return the value of EXPDB.EXPEDITE_ROLE_INFO.form_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLE_INFO.form_name
     *
     * @param formName the value for EXPDB.EXPEDITE_ROLE_INFO.form_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setFormName(String formName) {
        this.formName = formName == null ? null : formName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLE_INFO.description
     *
     * @return the value of EXPDB.EXPEDITE_ROLE_INFO.description
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLE_INFO.description
     *
     * @param description the value for EXPDB.EXPEDITE_ROLE_INFO.description
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLE_INFO.data_limit
     *
     * @return the value of EXPDB.EXPEDITE_ROLE_INFO.data_limit
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public Integer getDataLimit() {
        return dataLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLE_INFO.data_limit
     *
     * @param dataLimit the value for EXPDB.EXPEDITE_ROLE_INFO.data_limit
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setDataLimit(Integer dataLimit) {
        this.dataLimit = dataLimit;
    }
}