package com.probridge.expedite.model.expdb;

import java.io.Serializable;
import java.util.Date;

public class UserRoles extends UserRolesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLES.user_role_expiration
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    private Date userRoleExpiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLES.user_role_expiration
     *
     * @return the value of EXPDB.EXPEDITE_ROLES.user_role_expiration
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    public Date getUserRoleExpiration() {
        return userRoleExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLES.user_role_expiration
     *
     * @param userRoleExpiration the value for EXPDB.EXPEDITE_ROLES.user_role_expiration
     *
     * @mbggenerated Mon Jul 14 16:17:18 CST 2014
     */
    public void setUserRoleExpiration(Date userRoleExpiration) {
        this.userRoleExpiration = userRoleExpiration;
    }
}