package com.probridge.expedite.model.expdb;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_name
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_password
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_group
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_description
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_type
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_enabled
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private String userEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private Date userExpiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_USERS.user_pwd_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private Date userPwdExpiration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPDB.EXPEDITE_USERS
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_name
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_name
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_name
     *
     * @param userName the value for EXPDB.EXPEDITE_USERS.user_name
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_password
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_password
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_password
     *
     * @param userPassword the value for EXPDB.EXPEDITE_USERS.user_password
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_group
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_group
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserGroup() {
        return userGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_group
     *
     * @param userGroup the value for EXPDB.EXPEDITE_USERS.user_group
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup == null ? null : userGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_description
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_description
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserDescription() {
        return userDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_description
     *
     * @param userDescription the value for EXPDB.EXPEDITE_USERS.user_description
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserDescription(String userDescription) {
        this.userDescription = userDescription == null ? null : userDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_type
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_type
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_type
     *
     * @param userType the value for EXPDB.EXPEDITE_USERS.user_type
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_enabled
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_enabled
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public String getUserEnabled() {
        return userEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_enabled
     *
     * @param userEnabled the value for EXPDB.EXPEDITE_USERS.user_enabled
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserEnabled(String userEnabled) {
        this.userEnabled = userEnabled == null ? null : userEnabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_expiration
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public Date getUserExpiration() {
        return userExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_expiration
     *
     * @param userExpiration the value for EXPDB.EXPEDITE_USERS.user_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserExpiration(Date userExpiration) {
        this.userExpiration = userExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_USERS.user_pwd_expiration
     *
     * @return the value of EXPDB.EXPEDITE_USERS.user_pwd_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public Date getUserPwdExpiration() {
        return userPwdExpiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_USERS.user_pwd_expiration
     *
     * @param userPwdExpiration the value for EXPDB.EXPEDITE_USERS.user_pwd_expiration
     *
     * @mbggenerated Mon Feb 10 23:16:09 CST 2014
     */
    public void setUserPwdExpiration(Date userPwdExpiration) {
        this.userPwdExpiration = userPwdExpiration;
    }
}