package com.probridge.expedite.model.expdb;

import java.io.Serializable;

public class UserRolesKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLES.user_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPDB.EXPEDITE_ROLES.user_roles
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private String userRoles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EXPDB.EXPEDITE_ROLES
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLES.user_name
     *
     * @return the value of EXPDB.EXPEDITE_ROLES.user_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLES.user_name
     *
     * @param userName the value for EXPDB.EXPEDITE_ROLES.user_name
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPDB.EXPEDITE_ROLES.user_roles
     *
     * @return the value of EXPDB.EXPEDITE_ROLES.user_roles
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public String getUserRoles() {
        return userRoles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPDB.EXPEDITE_ROLES.user_roles
     *
     * @param userRoles the value for EXPDB.EXPEDITE_ROLES.user_roles
     *
     * @mbggenerated Sat May 17 20:23:57 CST 2014
     */
    public void setUserRoles(String userRoles) {
        this.userRoles = userRoles == null ? null : userRoles.trim();
    }
}